"""
Medical Appointment No-Show Risk Predictor
Streamlit App — deploy with: streamlit run app.py

Required files (generated by notebook Section 19):
  model.pkl          — trained XGBoost classifier
  features.pkl       — list of feature column names
  model_config.json  — threshold + metadata
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
import json
import os

# ── Page config ────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="No-Show Risk Predictor",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Load model artefacts ───────────────────────────────────────────────────
@st.cache_resource
def load_model():
    with open("models/model.pkl", "rb") as f:
        model = pickle.load(f)
    with open("models/features.pkl", "rb") as f:
        feature_cols = pickle.load(f)
    with open("models/model_config.json") as f:
        config = json.load(f)
    return model, feature_cols, config

try:
    model, FEATURE_COLS, config = load_model()
    THRESHOLD = config.get("optimal_threshold", 0.30)
    MODEL_AUC  = config.get("model_roc_auc", 0.0)
    BASELINE   = config.get("no_show_rate", 0.097)
    model_loaded = True
except FileNotFoundError:
    model_loaded = False

# ── Sidebar: patient input form ────────────────────────────────────────────
st.sidebar.header("📋 Patient & Appointment Details")
st.sidebar.markdown("---")

with st.sidebar:
    st.subheader("Demographics")
    age   = st.slider("Patient Age", 0, 100, 35)
    gender = st.selectbox("Gender", ["Female", "Male", "Other"])

    st.subheader("Appointment")
    shift = st.selectbox("Appointment Shift", ["morning", "afternoon"])
    day_of_week = st.selectbox(
        "Day of Week",
        ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    )
    month_name = st.selectbox(
        "Month",
        ["jan","feb","mar","april","may","june","july","aug","sept","oct","nov","dec"],
    )

    st.subheader("Patient Flags")
    needs_companion = st.checkbox("Needs a companion")
    over_60   = st.checkbox("Over 60 years old", value=(age > 60))
    under_12  = st.checkbox("Under 12 years old", value=(age < 12))

    st.subheader("Weather Conditions")
    avg_temp = st.slider("Average Temp on Appointment Day (°C)", -5, 45, 22)
    rainy_day_before  = st.checkbox("Rainy day before appointment")
    storm_day_before  = st.checkbox("Storm day before appointment")
    rain_intensity = st.selectbox("Rain Intensity", ["none", "light", "moderate", "heavy"])
    heat_intensity = st.selectbox("Heat Intensity", ["cool", "mild", "warm", "hot"])

    predict_btn = st.sidebar.button("🔮 Predict No-Show Risk", use_container_width=True, type="primary")

# ── Feature engineering: must match notebook exactly ──────────────────────
def build_feature_row(
    age, gender, shift, day_of_week, month_name,
    needs_companion, over_60, under_12,
    avg_temp, rainy_day_before, storm_day_before,
    rain_intensity, heat_intensity,
):
    month_map = {
        'jan': 1, 'feb': 2, 'mar': 3, 'april': 4, 'may': 5, 'june': 6,
        'july': 7, 'aug': 8, 'sept': 9, 'oct': 10, 'nov': 11, 'dec': 12,
    }
    dow_map = {
        "Monday": 0, "Tuesday": 1, "Wednesday": 2,
        "Thursday": 3, "Friday": 4, "Saturday": 5, "Sunday": 6,
    }
    age_group = "Child" if age < 18 else ("Senior" if age >= 60 else "Adult")

    row = {
        "age":                     age,
        "over_60_years_old":       int(over_60),
        "under_12_years_old":      int(under_12),
        "patient_needs_companion": int(needs_companion),
        "average_temp_day":        avg_temp,
        "rainy_day_before":        int(rainy_day_before),
        "storm_day_before":        int(storm_day_before),
        "day_of_week":             dow_map[day_of_week],
        "month_num":               month_map[month_name],
        # One-hot encoded
        # These names match the fitted model's serialized feature schema.
        "gender_F":                int(gender == "Female"),
        "gender_I":                int(gender == "Other"),
        "gender_M":                int(gender == "Male"),
        "appointment_shift_morning":   int(shift == "morning"),
        "appointment_shift_afternoon": int(shift == "afternoon"),
        "rain_intensity_no_rain":  int(rain_intensity == "none"),
        "rain_intensity_weak":     int(rain_intensity == "light"),
        "rain_intensity_moderate": int(rain_intensity == "moderate"),
        "rain_intensity_heavy":    int(rain_intensity == "heavy"),
        "heat_intensity_cold":     int(heat_intensity == "cool"),
        "heat_intensity_heavy_cold": 0,
        "heat_intensity_heavy_warm": int(heat_intensity == "hot"),
        "heat_intensity_mild":     int(heat_intensity == "mild"),
        "heat_intensity_warm":     int(heat_intensity == "warm"),
        "heat_intensity_hot":      int(heat_intensity == "hot"),
        "age_group_Child":         int(age_group == "Child"),
        "age_group_Adult":         int(age_group == "Adult"),
        "age_group_Senior":        int(age_group == "Senior"),
    }
    return row

def align_to_model(row_dict, feature_cols):
    """Align input to exact feature columns the model was trained on."""
    df = pd.DataFrame([row_dict])
    for col in feature_cols:
        if col not in df.columns:
            df[col] = 0
    return df[feature_cols]

# ── Risk gauge HTML ────────────────────────────────────────────────────────
def risk_gauge(prob: float) -> str:
    pct = int(prob * 100)
    if prob < 0.25:
        colour = "#27ae60"
        label  = "LOW RISK"
    elif prob < 0.50:
        colour = "#f39c12"
        label  = "MODERATE RISK"
    elif prob < 0.75:
        colour = "#e67e22"
        label  = "HIGH RISK"
    else:
        colour = "#c0392b"
        label  = "VERY HIGH RISK"

    return f"""
    <div style="text-align:center; padding: 20px 0;">
      <div style="font-size:14px; color:#666; margin-bottom:6px;">No-Show Probability</div>
      <div style="font-size:72px; font-weight:900; color:{colour}; line-height:1;">{pct}%</div>
      <div style="display:inline-block; background:{colour}; color:white;
                  padding:5px 18px; border-radius:20px; font-size:14px;
                  font-weight:600; letter-spacing:1px; margin-top:8px;">
        {label}
      </div>
    </div>
    """

# ── Main UI ────────────────────────────────────────────────────────────────
st.title("🏥 Medical Appointment No-Show Risk Predictor")
st.markdown(
    "Predict whether a patient is likely to miss their appointment using a trained XGBoost model. "
    "Fill in the sidebar and click **Predict**."
)

if not model_loaded:
    st.warning(
        "⚠️ Model files not found. Run the notebook through **Section 19** first to generate "
        "`model.pkl`, `features.pkl`, and `model_config.json`, then place them in the same "
        "directory as `app.py`."
    )
    st.stop()

# ── Metrics row ────────────────────────────────────────────────────────────
col1, col2, col3 = st.columns(3)
col1.metric("Model", "XGBoost")
col2.metric("ROC-AUC", f"{MODEL_AUC:.3f}")
col3.metric("Population No-Show Rate", f"{BASELINE*100:.1f}%")

st.markdown("---")

# ── Prediction ────────────────────────────────────────────────────────────
if predict_btn:
    row = build_feature_row(
        age, gender, shift, day_of_week, month_name,
        needs_companion, over_60, under_12,
        avg_temp, rainy_day_before, storm_day_before,
        rain_intensity, heat_intensity,
    )
    X_input = align_to_model(row, FEATURE_COLS)
    prob = model.predict_proba(X_input)[0][1]
    pred = int(prob >= THRESHOLD)

    left, right = st.columns([1, 1])

    with left:
        st.subheader("Risk Score")
        st.markdown(risk_gauge(prob), unsafe_allow_html=True)
        st.markdown(
            f"<div style='text-align:center; color:#888; font-size:12px;'>"
            f"Decision threshold: {THRESHOLD:.2f} | "
            f"Population baseline: {BASELINE*100:.1f}%</div>",
            unsafe_allow_html=True,
        )

    with right:
        st.subheader("Patient Summary")
        st.markdown(f"""
        | Field | Value |
        |---|---|
        | Age | {age} ({('Child' if age < 18 else 'Senior' if age >= 60 else 'Adult')}) |
        | Gender | {gender} |
        | Appointment | {shift.capitalize()}, {day_of_week} ({month_name}) |
        | Avg Temp | {avg_temp}°C ({heat_intensity}) |
        | Rain | {rain_intensity} {'☔' if rainy_day_before else ''} |
        | Companion needed | {'Yes' if needs_companion else 'No'} |
        """)

        if pred == 1:
            st.error(
                f"🚨 **High No-Show Risk** — this patient is predicted to miss their appointment "
                f"(probability {prob:.1%} ≥ threshold {THRESHOLD:.0%}). "
                "Consider a reminder call or overbooking slot."
            )
        else:
            st.success(
                f"✅ **Low No-Show Risk** — this patient is likely to attend "
                f"(probability {prob:.1%} < threshold {THRESHOLD:.0%})."
            )

    # ── SHAP waterfall if shap is installed ───────────────────────────────
    st.markdown("---")
    st.subheader("🔍 Why this prediction? (SHAP Explanation)")

    try:
        import shap
        import matplotlib.pyplot as plt
        
        @st.cache_resource
        def get_shap_explainer_rf():
            with open("models/model_rf.pkl", "rb") as f:
                rf = pickle.load(f)
            return shap.TreeExplainer(rf),rf

        with st.spinner("Computing SHAP explanation..."):
            explainer_rf_app, rf_app = get_shap_explainer_rf()
            sv = explainer_rf_app.shap_values(X_input)
            if isinstance(sv, list):
                sv_single = np.array(sv[1]).flatten()
            else:
                sv_single = np.array(sv).flatten()
            sv_single = sv_single[:len(FEATURE_COLS)]
            
        # Top contributing features
        top_idx = np.argsort(np.abs(sv_single))[-8:]
        vals = sv_single[top_idx]
        names = [FEATURE_COLS[i] for i in top_idx]

        shap_df = pd.DataFrame({
            "Feature": names,
            "SHAP Value": [round(float(v), 4) for v in vals],
            "Direction": ["↑ increases risk" if float(v) > 0 else "↓ decreases risk" for v in vals]
        }).sort_values("SHAP Value", key=abs, ascending=False)
        st.dataframe(shap_df, use_container_width=True, hide_index=True)

        colors = ['#DD8452' if float(v) > 0 else '#4C72B0' for v in vals]
        fig, ax = plt.subplots(figsize=(8, 4))
        ax.barh(names, [float(v) for v in vals], color=colors, edgecolor='white')
        ax.axvline(0, color='black', linewidth=0.8)
        ax.set_title("Top features driving this prediction\nOrange = increases risk  |  Blue = decreases risk",
                     fontweight='bold', fontsize=11)
        ax.set_xlabel("SHAP value")
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

    except ImportError:
        st.info(
            "Install **shap** to see individual feature explanations: `pip install shap`"
        )
    except Exception as e:
        st.info(f"SHAP explanation unavailable: {e}")

else:
    # Landing state
    st.info("👈 Fill in the patient details in the sidebar and click **Predict No-Show Risk**.")

    with st.expander("ℹ️ About this model"):
        st.markdown(f"""
        **Model:** XGBoost gradient boosting classifier  
        **Training data:** Brazilian healthcare appointment records (enriched with weather data)  
        **Target:** Predict if a patient will miss their appointment (no-show = yes)  
        **Class imbalance:** ~9.7% of appointments are no-shows — handled via `scale_pos_weight`  
        **Evaluation:** ROC-AUC, Precision-Recall AUC, F1 on minority class  
        **Threshold:** Optimised via F1 sweep (not the naive 0.50 default)  
        **Explainability:** SHAP TreeExplainer for both global and patient-level explanations  

        **Notebook sections:**  
        - Sections 1–7: EDA and visualisations  
        - Section 8–9: Feature engineering and preprocessing  
        - Sections 10–14: Model training, CV, ROC/PR curves, threshold optimisation  
        - Section 16: SMOTE oversampling  
        - Section 17: XGBoost (this model)  
        - Section 18: SHAP explainability  
        - Section 19: Model serialisation  
        """)

# ── Footer ─────────────────────────────────────────────────────────────────
st.markdown("---")
st.caption(
    "Built with XGBoost · SHAP · scikit-learn · Streamlit · imbalanced-learn  |  "
    "End-to-end ML project — Brazilian Medical Appointments Dataset"
)
